logging_dir: "../logs"
logfile_name: "bertopic_trainer_logs.txt"
logging_level: "DEBUG"

study_name: "top_params_finetuning_3"
study_storage_filename: "distilled_model_choice_experiments_dataset5.sql"

dataset_path: "../../dataset"
models_path: "../../models"

batch_size: 768
dataset_index: 5
n_trials: 25200

hyperparameters:
  model_name: [
    'sentence-transformers/distilroberta-base-paraphrase-v1',
  ]

  nr_topics: [50, 100, 175, 180, 185, 190, 195, 200, 250]
  top_n_words: [30]
  min_topic_size: [15, 250, 500, 800, 1500, 2000]
  n_gram_range_start: [ 1 ]
  n_gram_range_end: [ 1 ]
  
  # count vectorizer params
  max_features: [60000]
  max_df: [0.88, 0.9, 0.93, 0.96]
  min_df: [0.1, 0.13, 0.17]
  lowercase: [true]

  # umap params
  n_neighbors: [25, 30, 35, 40, 45]
  n_components: [256]
  umap_metric: ['euclidean']
  n_epochs: [200]
  learning_rate: [1.0]
  min_dist: [0.1]
  random_state: [65]

  # hdbscan params
  min_cluster_size: [25, 35, 45, 55, 85, 120, 300, 500]
  cluster_selection_epsilon: [0.0]
  hdbscan_metric:  ['euclidean']
  cluster_selection_method: ['eom']

  # metrics params
  topk: [10]