logging_dir: "../logs"
logfile_name: "bertopic_trainer_logs.txt"
logging_level: "DEBUG"

study_name: "distilled_model_choice_sample_dataset2"

dataset_path: "../../dataset"
models_path: "../../models"

batch_size: 384
dataset_index: 5
n_trials: 288

hyperparameters:
  model_name: [
    'sentence-transformers/distilroberta-base-paraphrase-v1',
    'sentence-transformers/stsb-distilroberta-base-v2',
    'sentence-transformers/distilbert-base-nli-stsb-quora-ranking',
    'distilbert-base-nli-mean-tokens'
  ]

  nr_topics: [15, 75, 160, 210, 300, 400]
  top_n_words: [10, 30, 80, 120]
  min_topic_size: [15]
#  n_gram_range: [(1, 1), (1,2), (1,3)]
  n_gram_range: [[1, 1]]
  
#  # TODO inputs for hyperparameters
#  min_categories: 5
#  max_categories: 5
  
  # count vectorizer params
  max_features: [60000]
  max_df: [0.999]
  min_df: [0.001]
  lowercase: [true]

  # umap params
  n_neighbors: [3, 15, 40]
  n_components: [256]
  umap_metric: ['euclidean']
  n_epochs: [200]
  learning_rate: [1.0]
  min_dist: [0.1]
  random_state: [65]

  # hdbscan params
  min_cluster_size: [5]
  cluster_selection_epsilon: [0.0]
  hdbscan_metric:  ['euclidean']
  cluster_selection_method: ['eom']

  # metrics params
  topk: [10]