logging_dir: "../logs"
logfile_name: "bertopic_trainer_logs.txt"
logging_level: "DEBUG"

study_name: "tuning_dataset5_study2"
study_storage_filename: "dataset5_finetuning.sql"

dataset_path: "../../dataset"
models_path: "../../models"

batch_size: 768
dataset_index: 5
n_trials: 640

hyperparameters:
  model_name: [
    'sentence-transformers/distilroberta-base-paraphrase-v1',
  ]

  nr_topics: [ 175, 180, 185, 190 ]
  top_n_words: [80]
  min_topic_size: [5]
  n_gram_range_start: [ 1 ]
  n_gram_range_end: [ 1 ]
  
  # count vectorizer params
  max_features: [30000]
  max_df: [0.93]
  min_df: [0.1]
  lowercase: [true]

  # umap params
  n_neighbors: [45]
  n_components: [ 64 ]
  umap_metric: ['euclidean']
  n_epochs: [200]
  learning_rate: [1.0]
  min_dist: [0.2, 0.3, 0.5, 0.8]
  random_state: [65]

  # hdbscan params
  min_cluster_size: [ 1, 5, 15, 30, 45 ]
  cluster_selection_epsilon: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  hdbscan_metric:  ['euclidean']
  cluster_selection_method: ['leaf']

  # metrics params
  topk: [10]