logging_dir: "../logs"
logfile_name: "bertopic_trainer_logs.txt"
logging_level: "DEBUG"

study_name: "gen_embeddings_ds5"
study_storage_filename: "generate_embeddings.sql"

dataset_path: "../../dataset"
models_path: "../../models"

batch_size: 128
dataset_index: 5
n_trials: 1

hyperparameters:
  model_name: [
    'allenai/scibert_scivocab_uncased'
  ]

  nr_topics: [320]
  top_n_words: [80]
  min_topic_size: [30]
  n_gram_range_start: [ 1 ]
  n_gram_range_end: [ 1 ]
  
  # count vectorizer params
  max_features: [10000]
  max_df: [0.93]
  min_df: [0.1]
  lowercase: [true]

  # umap params
  n_neighbors: [40]
  n_components: [256]
  umap_metric: ['euclidean']
  n_epochs: [200]
  learning_rate: [1.0]
  min_dist: [0.1]
  random_state: [65]

  # hdbscan params
  min_cluster_size: [45]
  cluster_selection_epsilon: [0.0]
  hdbscan_metric:  ['euclidean']
  cluster_selection_method: ['eom']

  # metrics params
  topk: [10]