logging_dir: "../logs"
logfile_name: "bertopic_trainer_logs.txt"
logging_level: "DEBUG"

study_name: "dataset5_partial_fit"
study_storage_filename: "dataset5_partialfit.sql"

dataset_path: "../../dataset"
models_path: "../../models"

batch_size: 768
dataset_index: 5
n_trials: 90

hyperparameters:
  model_name: [
    'sentence-transformers/distilroberta-base-paraphrase-v1',
  ]

  nr_topics: [ 1200 ]
  top_n_words: [80]
  min_topic_size: [30]
  n_gram_range_start: [ 1 ]
  n_gram_range_end: [ 1 ]
  
  # count vectorizer params
  max_features: [10000]
  max_df: [0.93]
  min_df: [0.1]
  lowercase: [true]

  # umap params
  n_neighbors: [45]
  n_components: [ 256 ]
  umap_metric: ['euclidean']
  n_epochs: [200]
  learning_rate: [1.0]
  min_dist: [0.1]
  random_state: [65]

  # hdbscan params
  min_cluster_size: [ 5, 20, 30, 54, 75, 100, 200, 400, 600, 950 ]
  cluster_selection_epsilon: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  hdbscan_metric:  ['euclidean']
  cluster_selection_method: ['eom']

  # metrics params
  topk: [10]